Client: Entities: Add missing Logger import
When building with DEBUG on Linux the following failure appears:

    GameLogic/Entities.cs(144,17): error CS0103: The name 'Log' does not exist in the current context [/home/marijn/Code/C#/Nitrox/NitroxClient/NitroxClient.csproj]

Fixes: 0baaddb1e0a3596ad43da0390554ba819aa2a797